
robot_arm_names: ["arm"]

scan_joints_arm: 
  - [-0.130, -1.358, -0.790, -2.289, 0.043, 1.269, 1.023]
  - [1.161,  -0.519, -1.678, -1.345, 0.278, 0.985, 0.489]
  - [0.035, 0.079, 0.000, -1.229, 0.0741, 0.977, 0.890]
  - [-1.076, -0.981, 1.051, -1.420, 0.233, 0.977, 0.681]
  - [-0.303, -1.214,  0.812, -1.754, 0.168, 1.118, 0.999]
drop_joints_arm: [-0.303, -1.214,  0.812, -1.754, 0.168, 1.118, 0.999]  # TODO set correctly
home_joints_arm: [0, -2.26893, 0.5235, 0, 0.698132, 0, 2.35619]  # TODO set correctly
ready_joints_arm:  [0.15707963, -1.58824962,  0.55850536,  0.31415927,  1.23918377, -0.78539816,  0.54105207]  # TODO set correctly
search_joints_arm: [-0.36651914, -1.79768913,  1.04719755,  1.79768913,  0.27925268, 0.2443461 ,  1.34390352]  # TODO set correctly

base_frame_id: "panda_link0"

arm_velocity_scaling_drop: 0.5
arm_velocity_scaling_grasp: 0.2

pregrasp_offset_z: -0.05
